- hosts: webservers
  tasks:
    - name: Update cache 
      yum:
       update_cache: true
      become: true



    - name: Install podman
      ansible.builtin.yum:
        name: "podman"
        state: present
      become: true

    - name: Login to registry and create ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        username: acrlabfran
        password: 'xxx'
        registry: acrlabfran.azurecr.io
      become: true

    - name: Pull an image
      containers.podman.podman_image:
        name: acrlabfran.azurecr.io/nginx:casopractico2
      become: true
    
    