- hosts: webservers
  tasks:
    - name: Update cache 
      yum:
       update_cache: true
      become: true



    - name: Install podman
      ansible.builtin.yum:
        name: "podman"
        state: present
      become: true

    - name: Login to registry and create ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        username: acrlabfran
        password: 'pSNOig8T3BhEFaMP7/H7JodAQov30VcJBDHOzD4xi3+ACRBq7uVi'
        registry: acrlabfran.azurecr.io
      become: true

    - name: Pull an image
      containers.podman.podman_image:
        name: acrlabfran.azurecr.io/nginx:casopractico2
      become: true

    - name: create container
      containers.podman.podman_container:
        name: web-server
        image: acrlabfran.azurecr.io/nginx:casopractico2
        state: started
        detach: true
        exposed_ports:
         - 443
        ports:
         - 80:443
         - 443:443
      become: true

    - name: Allow all access to tcp port 80 and 443
      community.general.ufw:
        rule: allow
        port: '80,443'
        proto: tcp
      become: true
    